# Generated by Django 5.2.6 on 2025-09-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='source',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.CreateModel(
            name='AirportNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_parent', to='flights.airportnode')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_parent', to='flights.airportnode')),
            ],
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
